-- Sessions are per (phone, business) — coexistence pilot findings, 2026-08-12.
-- Apply once in the Supabase SQL editor. Requires Postgres 15+ (NULLS NOT
-- DISTINCT); Supabase has shipped 15+ for years.
--
-- WHY: one phone can hold live conversations with TWO tenants' bots at once.
-- Live evidence from the pilot: the kids-business owner's phone (972528250088)
-- also has a session with the DIVAZ business. With sessions unique on
-- session_id alone, (a) her owner-echo standdown landed on the DIVAZ-bound
-- session row, and (b) every message to the kids bot re-pointed the single row
-- back and forth between the two businesses, sharing stage/history state
-- across tenants.
--
-- The server code on fix/coexistence-pilot-findings works under BOTH schemas:
--   before this file — inserts of a second (session_id, business) row fail on
--   the old unique constraint and the code falls back to today's single-row
--   re-point behaviour;
--   after this file — each business gets its own session row per phone, and
--   standdown reads/writes, stage updates and history loads are all scoped to
--   the (session_id, business_id) pair.
--
-- NOTE for repo tooling (not the server): wa-studio/tests/* helpers still
-- upsert sessions with onConflict:'session_id'; they are manual dev scripts
-- and will need the same update-then-insert treatment when next used.

begin;

-- ── 1. Echo auto-reply grace window (pilot finding #2) ───────────────────────
-- The client's WhatsApp Business app had an automatic greeting: customer
-- writes -> app auto-replies in ~2s -> echo -> 12h standdown, silencing the
-- bot for the exact lead it was supposed to answer. An echo landing within
-- this many seconds of the customer's own message is classified
-- auto_reply_suspected and does NOT arm the standdown. 0 turns the immunity
-- off. The server defaults to 25 when the column is absent (fail-soft).
alter table business_profiles
  add column if not exists standdown_echo_grace_seconds integer not null default 25;

comment on column business_profiles.standdown_echo_grace_seconds is
  'Owner echoes arriving within this many seconds of the customer''s last inbound message are treated as the app''s automatic reply (no standdown). 0 disables the immunity. Default 25.';

-- ── 2. sessions: unique per (session_id, business_id), not per session_id ────

-- 2a. Drop every PRIMARY KEY / UNIQUE constraint on exactly (session_id).
-- The original table was created with `session_id TEXT PRIMARY KEY`; the
-- constraint name may vary between environments, so it is looked up rather
-- than assumed. CASCADE also removes any foreign keys that referenced the
-- constraint (none are relied on by the server; deletes are explicit in code).
do $$
declare
  con record;
begin
  for con in
    select c.conname
    from pg_constraint c
    where c.conrelid = 'public.sessions'::regclass
      and c.contype in ('p', 'u')
      and (
        select array_agg(a.attname::text order by k.ord)
        from unnest(c.conkey) with ordinality as k(attnum, ord)
        join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum
      ) = array['session_id']
  loop
    raise notice 'sessions: dropping constraint %', con.conname;
    execute format('alter table public.sessions drop constraint %I cascade', con.conname);
  end loop;
end $$;

-- 2b. Same for any bare unique INDEX on exactly (session_id) that is not
-- constraint-backed (defensive — none is expected).
do $$
declare
  idx record;
begin
  for idx in
    select i.indexrelid::regclass as idxname
    from pg_index i
    where i.indrelid = 'public.sessions'::regclass
      and i.indisunique
      and i.indnatts = 1
      and not exists (select 1 from pg_constraint c where c.conindid = i.indexrelid)
      and (select a.attname from pg_attribute a
           where a.attrelid = i.indrelid and a.attnum = i.indkey[0]) = 'session_id'
  loop
    raise notice 'sessions: dropping unique index %', idx.idxname;
    execute format('drop index %s', idx.idxname);
  end loop;
end $$;

-- 2c. The table lost its primary key in 2a — give it a surrogate one.
-- (Nothing in the server addresses sessions by this id; it exists so the
-- table keeps a PK for Supabase tooling and future replication.)
alter table public.sessions
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.sessions'::regclass and contype = 'p'
  ) then
    alter table public.sessions add constraint sessions_pkey primary key (id);
  end if;
end $$;

-- 2d. The new law: one session per (phone, business). NULLS NOT DISTINCT so
-- legacy/studio rows with business_id IS NULL cannot silently duplicate
-- either. Existing data cannot violate this (session_id was unique until 2a).
create unique index if not exists sessions_session_business_key
  on public.sessions (session_id, business_id) nulls not distinct;

comment on index sessions_session_business_key is
  'Sessions are per (phone, business): the same phone may hold separate conversations with different tenants'' bots (2026-08-13).';

-- ── 3. conversations view: expose business_id ────────────────────────────────
-- lib/context.js scopes history to the session''s business so one tenant''s
-- conversation never rides into another tenant''s model context. business_id
-- is appended LAST so CREATE OR REPLACE keeps the existing column order and,
-- crucially, the existing grants (the 2026-05-20 hardening revoked anon).
create or replace view conversations as
  select session_id, 'user'      as role, user_message   as content, stage, created_at, business_id
    from conversation_messages where user_message  is not null
  union all
  select session_id, 'assistant' as role, agent_response as content, stage, created_at, business_id
    from conversation_messages where agent_response is not null;

commit;
